###    NOTIFICACIONES    ###
NOTIF_SALIR = -1
NOTIF_ERROR = -1
NOTIF_EXITO = 0
NOTIF_CONEXION_OK = 1
NOTIF_CONEXION_ERROR = 2
NOTIF_CONEXION_TEST = 3
NOTIF_USUARIO_CONECTADO = 4
NOTIF_USUARIO_DESCONECTADO = 5
NOTIF_MENSAJE_RECIBIDO = 6
NOTIF_OPERACION_EXITOSA = 9
NOTIF_OPERACION_ERROR = 10
NOTIF_INICIO_SESION = 11
NOTIF_CONTACTO = 12
NOTIF_REGISTRO = 13
NOTIF_DATOS_REGISTRO = 20
NOTIF_BUSQUEDA = 21

MAX_BYTES = 1024

###   PAQUETES RECIBIDOS  ###
PAQ_CONEXION = 1
PAQ_MENSAJE = 2
PAQ_REGISTRO = 3
PAQ_CONTACTO = 10
PAQ_HISTORIAL = 55
PAQ_RESPUESTA = 88
PAQ_TEST = 99
PAQ_BUSQUEDA = 707

### COLORES ###
PRIMARIO = "#2874A6"
SECUNDARIO = "#219900"
CONECTADO_FONDO = "#219900"
CONECTADO_LETRA = "white"
DESCONECTADO_FONDO = "#808B96"
DESCONECTADO_LETRA = "white"
NOTIFICACION_FONDO = "red"
NOTIFICACION_LETRA = "white"
LABEL_1 = "black"
LABEL_2 = "white"
BOTON_1 = "white"
FONDO_VENTANA = "#d9d9d9"
LABEL_FONDO = FONDO_VENTANA
CLOSE = "red"
PERFIL = "#0A9E90"
FONDO_CHAT = "#ece5dd"
FONDO_CONTACTOS = "white"

## FUENTES ###
MAX_CARACTERES = 15
ESPACIADO = int(MAX_CARACTERES/4)*' '
FUENTE_PRED = "Ubuntu"
